version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: triple-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=triple-db
      - MYSQL_USER=soyeon
      - MYSQL_PASSWORD=1234
  redis:
    image: redis
    container_name: triple-redis
    ports:
      - "6379:6379"

